services:
  app:
    build:
      context: .
      dockerfile: dockerfile.devcontainer
    tty: true
    volumes:
      - ../:/app
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
